version: '3'
services:
  postgres:
    image: postgres:alpine
    tty: true
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

  adminer:
    image: adminer:4.8.1-standalone
    tty: true
    ports:
      - 9001:8080
    depends_on:
      - postgres

  app:
    build:
      context: .
      dockerfile: ./docker/app/local.Dockerfile
      args:
        VERSION: 2.0.2
    tty: true
    ports:
      - 9000:5000
    volumes:
      - .:/root/project
